export const ItemData = [
  {
    name: "Croissant",
    category: "Viennoiserie",
    price: 100,
    id: "1",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Pain au Chocolat",
    category: "Viennoiserie",
    price: 110,
    id: "2",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Pain aux Raisins",
    category: "Viennoiserie",
    price: 160,
    id: "3",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Chausson aux Pommes",
    category: "Viennoiserie",
    price: 160,
    id: "4",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Cookie",
    category: "Viennoiserie",
    price: 150,
    id: "5",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Croissant aux Amandes",
    category: "Viennoiserie",
    price: 160,
    id: "6",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Brioche",
    category: "Viennoiserie",
    price: 100,
    id: "7",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Suisse",
    category: "Viennoiserie",
    price: 160,
    id: "8",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Baguette",
    category: "Pain",
    price: 105,
    id: "9",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Tarte au Citron",
    category: "Pâtisserie",
    price: 350,
    id: "10",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Eau 50cl",
    category: "Boissons",
    price: 120,
    id: "11",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Sandwich",
    category: "Snacking",
    price: 380,
    id: "12",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Eclair au chocolat",
    category: "Pâtisserie",
    price: 280,
    id: "13",
    vatIn: 0.1,
    vatOut: 0.055,
  },
  {
    name: "Flan",
    category: "Pâtisserie",
    price: 280,
    id: "14",
    vatIn: 0.1,
    vatOut: 0.055,
  },
];
